/**
 * Case Study Detail Page — /case-studies/{slug} (EN)
 *
 * Dynamic route rendering a single case study from `src/data/case-studies.ts`.
 * Follows the 13-section template (Part 5.1) in exact order:
 *   1 Hero (direct answer + breadcrumb)    8 Planned vs Actual
 *   2 Stats (4 facts)                      9 Results (+ ProTip 2)
 *   3 At a Glance (table)                   [mid CTA — Part 8]
 *   4 Challenge (+ ProTip 1)              10 FAQ (CSS accordion)
 *   5 Timeline (flagship SVG)             11 Related
 *   6 Steps (HowTo <ol>)                  12 Final CTA (reuses CTASection)
 *   7 Documents (table)                   13 Schema (JSON-LD)
 *
 * Schema stack (Part 12) is generated by `caseStudySchemaStack()` from
 * `src/lib/case-studies.ts`: Article + WebPage + BreadcrumbList +
 * (FAQPage) + (HowTo) + ImageObject*. Visible text = schema text
 * byte-for-byte (RULE 3 / Part 12 gate).
 *
 * Canonical + hreflang (en-AE / ar-AE / x-default) via `hreflangAlternates()`.
 *
 * @see plans/case-studies-mega-plan.md Part 5.1 / Part 8 / Part 12
 */

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { caseStudies } from "@/data/case-studies";
import { CASE_STUDIES_HUB_PATH, caseStudySchemaStack, caseStudyUrl } from "@/lib/case-studies";
import { SITE } from "@/lib/constants";
import { hreflangAlternates } from "@/lib/locale";
import type { BreadcrumbItem } from "@/lib/schema";

/* ── Case-study styles (design tokens, reveal/choreography) ── */
import "@/components/case-studies/case-studies.css";

/* ── Section Components (Part 5.1, 12 sections) ───────────── */
import CaseStudyHero from "@/components/case-studies/CaseStudyHero";
import CaseStudyPhoto from "@/components/case-studies/CaseStudyPhoto";
import CaseStudyStats from "@/components/case-studies/CaseStudyStats";
import CaseStudyAtGlance from "@/components/case-studies/CaseStudyAtGlance";
import CaseStudyChallenge from "@/components/case-studies/CaseStudyChallenge";
import CaseStudyTimeline from "@/components/case-studies/CaseStudyTimeline";
import CaseStudySteps from "@/components/case-studies/CaseStudySteps";
import CaseStudyDocuments from "@/components/case-studies/CaseStudyDocuments";
import CaseStudyBeforeAfter from "@/components/case-studies/CaseStudyBeforeAfter";
import CaseStudyResults from "@/components/case-studies/CaseStudyResults";
import CaseStudyFAQ from "@/components/case-studies/CaseStudyFAQ";
import CaseStudyRelated from "@/components/case-studies/CaseStudyRelated";
import CaseStudyCta from "@/components/case-studies/CaseStudyCta";

/* ============================================================
   Static Generation
   ============================================================ */

/** Generate a page for every case study at build time. */
export function generateStaticParams() {
  return caseStudies.map((study) => ({ slug: study.slug }));
}

/* ============================================================
   Dynamic Metadata
   ============================================================ */

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params;
  const study = caseStudies.find((s) => s.slug === slug);
  if (!study) return {};

  // Brand once, capped at 60 chars. `absolute` bypasses the root layout's
  // `%s | Wasleen Approvals` template so the brand is NOT appended a second
  // time (same pattern as about-us/page.tsx). seoTitle stays a plain string
  // because OG/twitter titles below must be strings.
  const seoTitle = `${study.seoTitle} | ${SITE.name}`.substring(0, 60);
  const description = study.description;

  const canonical = caseStudyUrl(study.slug, "en");

  // OG image — the case-study hero placeholder (blueprint-style WebP)
  const heroImage = study.images[0];
  const ogImage = heroImage
    ? {
        url: heroImage.src,
        width: heroImage.width,
        height: heroImage.height,
        alt: heroImage.alt,
      }
    : {
        url: "/images/OG%20Image%202.jpg",
        width: 1200,
        height: 630,
        alt: study.projectTitle,
      };

  return {
    title: { absolute: seoTitle },
    description,
    alternates: {
      canonical,
      languages: hreflangAlternates(SITE.url, `/case-studies/${study.slug}`),
    },
    openGraph: {
      title: seoTitle,
      description: description.substring(0, 160),
      url: canonical,
      type: "article",
      siteName: SITE.name,
      publishedTime: study.publishedAt,
      modifiedTime: study.lastUpdated,
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title: seoTitle,
      description: description.substring(0, 160),
      images: [ogImage.url],
    },
  };
}

/* ============================================================
   Page Component
   ============================================================ */

export default async function CaseStudyDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const study = caseStudies.find((s) => s.slug === slug);
  if (!study) notFound();

  const canonical = caseStudyUrl(study.slug, "en");

  /* ── Breadcrumbs (visible in hero + BreadcrumbList schema) ── */
  const breadcrumbs: BreadcrumbItem[] = [
    { position: 1, name: "Home", slug: "/" },
    { position: 2, name: "Case Studies", slug: CASE_STUDIES_HUB_PATH },
    { position: 3, name: study.projectTitle, slug: `/case-studies/${study.slug}` },
  ];

  /* ── Schema stack (Article + WebPage + BreadcrumbList + FAQ + HowTo + Images) ── */
  const schemas = caseStudySchemaStack(
    {
      study,
      url: canonical,
      title: study.seoTitle,
      description: study.description,
      breadcrumbs,
    },
    "en",
  );

  /* ── Render (13 sections, Part 5.1 order) ─────────────────── */

  return (
    <>
      {/* JSON-LD Schema (Section 13) */}
      {schemas.map((schema, i) => (
        <script
          key={i}
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
        />
      ))}

      {/* Section 1 — Hero / Direct Answer (breadcrumb + H1 + status chip) */}
      <CaseStudyHero study={study} breadcrumbs={breadcrumbs} />

      {/* Section 1.5 — Post-hero real photo (Part 18.4 — site photo, not logo) */}
      <CaseStudyPhoto study={study} />

      {/* Section 2 — Stats Strip (4 facts: authority, quoted fee, scope, status) */}
      <CaseStudyStats stats={study.stats} />

      {/* Section 3 — At a Glance (table) */}
      <CaseStudyAtGlance study={study} />

      {/* Section 4 — The Challenge (+ ProTip 1) */}
      <CaseStudyChallenge study={study} />

      {/* Section 5 — Timeline (flagship animated SVG) */}
      <CaseStudyTimeline study={study} />

      {/* Section 6 — What We Did (HowTo <ol>) */}
      <CaseStudySteps study={study} />

      {/* Section 7 — Documents & Requirements (table) */}
      <CaseStudyDocuments study={study} />

      {/* Section 8 — Planned vs Actual (before/after table) */}
      <CaseStudyBeforeAfter study={study} />

      {/* Section 9 — Results (+ ProTip 2) */}
      <CaseStudyResults study={study} />

      {/* Mid-page CTA (Part 8 — fires case_study_cta_click position=mid) */}
      <CaseStudyCta study={study} position="mid" />

      {/* Section 10 — FAQ (CSS-only accordion) */}
      <CaseStudyFAQ study={study} />

      {/* Section 11 — Related (cards + approval/guide links) */}
      <CaseStudyRelated study={study} />

      {/* Section 12 — Final CTA (reuses CTASection) */}
      <CaseStudyCta study={study} position="end" />
    </>
  );
}
